### ISSUE TITLE
Fixed version

### ISSUE THREAD

**Issue by viecabana** [clembu/ink-for-construct#2]
Concerning the version 1.0.0.1, it couldn’t be installed, so the user skymen fixed it so here is the link: [https://discord.com/channels/116497549237551109/253490735268102144/848940292447010848](url)

**Comment by henlo-birb** [comment]
that's not accessible outside of people on that discord, could you put it on github or somewhere else?

**Comment by clembu** [comment]
Thank you, and sorry for the delay! Version 1.0.1.1 should install without issues.
